conda_forge_output_validation: true

os_version:
  linux_64: cos7

# https://conda-forge.org/docs/maintainer/conda_forge_yml.html#azure
azure:
  # toggle for storing the conda build_artifacts directory (including the
  # built packages) as an Azure pipeline artifact that can be downloaded
  store_build_artifacts: true

  # Docker can't run podman (required for tests) without additional privileges
  settings_linux:
    variables:
      CONDA_FORGE_DOCKER_RUN_ARGS: --cap-add SYS_ADMIN
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
